workflows:
  android-native-release:
    name: Build Android APK Nativo
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - name: Entrar na pasta android e buildar
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/build/outputs/apk/release/*.apk